# Generated by Django 5.2 on 2025-06-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRodrigo', '0003_usuario_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroDeUsuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('equipe', models.CharField(max_length=10)),
            ],
        ),
    ]
