# Generated by Django 5.2 on 2025-06-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRodrigo', '0004_cadastrodeusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrodeusuario',
            name='equipe',
            field=models.CharField(max_length=100),
        ),
    ]
