# Generated by Django 5.2 on 2025-06-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRodrigo', '0005_alter_cadastrodeusuario_equipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refatoracao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('projeto', models.CharField(max_length=100)),
                ('equipe', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=100)),
            ],
        ),
    ]
